# Generated by Django 3.0.6 on 2020-06-03 06:03

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20200603_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phonenumber',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
