# Generated by Django 3.0.8 on 2020-09-02 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cutomeruserprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_gender', models.CharField(max_length=150)),
                ('customer_phonenumber', models.BigIntegerField(unique=True)),
                ('age', models.SmallIntegerField()),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
