# Generated by Django 3.0.8 on 2020-07-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_innerdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='innerdata',
            new_name='customerdata',
        ),
    ]
