# Generated by Django 3.0.8 on 2020-07-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200714_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='filedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150)),
                ('picture', models.ImageField(null=True, upload_to='photos/')),
            ],
        ),
    ]
