# Generated by Django 3.0.8 on 2020-07-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_memberdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdata',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.pgdata'),
        ),
    ]
