# Generated by Django 3.0.8 on 2020-07-16 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_memberdata_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdata',
            name='mname',
        ),
        migrations.AddField(
            model_name='memberdata',
            name='pg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.pgdata'),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='message',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
