# Generated by Django 3.0.8 on 2020-08-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200828_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_data',
            name='message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
