# Generated by Django 3.0.8 on 2020-08-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_data_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_data',
            name='message',
        ),
    ]
