# Generated by Django 3.0.6 on 2020-06-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='zone',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
