# Generated by Django 3.0.6 on 2020-06-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filex', '0002_details_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='person',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
