# Generated by Django 3.0.6 on 2020-06-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filex', '0003_details_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='item',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='name',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='time',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
