# Generated by Django 3.0.6 on 2020-06-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filex', '0004_auto_20200622_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('item', models.TextField()),
                ('time', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='details',
            name='item',
        ),
        migrations.RemoveField(
            model_name='details',
            name='name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='time',
        ),
    ]
