# Generated by Django 3.0.6 on 2020-06-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filex', '0006_auto_20200623_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='filesdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
    ]
