# Generated by Django 3.0.6 on 2020-06-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filex', '0007_filesdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesdata',
            old_name='images',
            new_name='myfile',
        ),
        migrations.RenameField(
            model_name='filesdata',
            old_name='name',
            new_name='myname',
        ),
    ]
