# Generated by Django 3.0.6 on 2020-06-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filex', '0008_auto_20200625_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesdata',
            name='myfile',
            field=models.ImageField(default='/media/default.jpg', upload_to='media/'),
        ),
    ]
