# Generated by Django 3.0.6 on 2020-06-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filex', '0010_remove_filesdata_myfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesdata',
            name='myfile',
            field=models.ImageField(default='/media/photos/default.jpg', upload_to='photos/'),
        ),
    ]
