# Generated by Django 3.0.6 on 2020-06-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filex', '0011_filesdata_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesdata',
            name='myfile',
            field=models.FileField(default='/media/photos/default.jpg', upload_to='photos/'),
        ),
    ]
