# Generated by Django 3.0.6 on 2020-06-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filex', '0012_auto_20200625_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesdata',
            name='myfile',
            field=models.ImageField(default='/media/photos/default.jpg', upload_to='photos/'),
        ),
    ]
