# Generated by Django 3.0.6 on 2020-06-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filex', '0013_auto_20200625_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='slidedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=150)),
                ('sfile', models.ImageField(default='/media/photos/default.jpg', upload_to='photos/')),
            ],
        ),
    ]
