# Generated by Django 3.0.8 on 2020-08-31 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=255)),
                ('end_point', models.CharField(max_length=255)),
                ('license_number', models.PositiveIntegerField()),
                ('registration_number', models.PositiveIntegerField()),
                ('service_days', models.SmallIntegerField()),
                ('age', models.SmallIntegerField()),
                ('shift', models.CharField(max_length=100)),
                ('charge_per_trip', models.SmallIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('aadhar_number', models.PositiveIntegerField()),
                ('owner_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
