# Generated by Django 3.0.8 on 2020-09-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensourceauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aadhar_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='license_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='registration_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
