# Generated by Django 3.0.8 on 2020-09-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensourceauth', '0002_auto_20200901_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
