# Generated by Django 3.0.8 on 2020-09-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensourceauth', '0003_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
