# Generated by Django 3.0.8 on 2020-09-03 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('opensourceauth', '0006_auto_20200902_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookings',
            name='charges',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbookings',
            name='endingpoint',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbookings',
            name='startingpoint',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
