# Generated by Django 3.0.8 on 2020-09-10 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_componenteach'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
