# Generated by Django 3.0.8 on 2020-09-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_component_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.IntegerField(unique=True)),
            ],
        ),
    ]
