# Generated by Django 3.0.8 on 2020-09-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_customerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='user_name',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
