# Generated by Django 3.0.8 on 2020-09-12 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_auto_20200912_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componenteach',
            old_name='name',
            new_name='cname',
        ),
    ]
