# Generated by Django 3.0.8 on 2020-09-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_auto_20200912_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='percentage',
            field=models.IntegerField(blank=True, default=30),
            preserve_default=False,
        ),
    ]
