# Generated by Django 3.0.8 on 2020-09-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_component_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
