# Generated by Django 3.0.8 on 2020-09-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0012_auto_20200916_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='reference_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
