# Generated by Django 3.0.8 on 2020-09-19 18:46

import components.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0013_auto_20200916_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.ImageField(default=0, upload_to=components.models.user_directory_path),
            preserve_default=False,
        ),
    ]
