# Generated by Django 3.0.8 on 2020-09-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0015_auto_20200923_0636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentupdate',
            old_name='due_data',
            new_name='due_date',
        ),
    ]
